---
- name: SETUP
  hosts: all
  gather_facts: false
  remote_user: root
  run_once: true
  tags: basic
  tasks:
    - name: update / upgrade packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: install packages
      apt:
        name: [telnet, git, vim, htop, nload, tmux, dstat, net-tools, nodejs]
        state: latest

    - name: disable show IP on login
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: ^(# *)?PrintLastLog
        line: PrintLastLog no
        
    - name: restart sshd
      service:
        name: sshd
        state: restarted

    - name: create app user
      user:
        name: app

    - name: create KEKS_TODO unit file
      copy:
        dest: /etc/systemd/system/KEKS_TODO.service
        content: |
          [Unit]
          Description=KEKS_TODO

          [Service]
          AmbientCapabilities=CAP_NET_BIND_SERVICE
          WorkingDirectory=/home/app/KEKS_TODO
          ExecStart=/usr/bin/node /home/app/KEKS_TODO/wwwroot/index.js
          Restart=always
          RestartSec=10
          KillSignal=SIGINT
          SyslogIdentifier=KEKS_TODO
          User=app

          [Install]
          WantedBy=multi-user.target

    - name: enable KEKS_TODO
      ansible.builtin.systemd:
        name: KEKS_TODO.service
        enabled: yes
        daemon_reload: yes


- name: BUILD
  hosts: all
  gather_facts: false
  #remote_user: root
  tags: deploy
  tasks:
    - name: BUILD
      local_action: shell cd ../todo; npm run build

- name: DEPLOY
  hosts: all
  tags: deploy
  gather_facts: false
  remote_user: root
  tasks: 
    - name: copy app
      ansible.posix.synchronize:
        src: ../todo/
        dest: /home/app/KEKS_TODO
        delete: yes
        recursive: yes

    - name: restart KEKS_TODO
      ansible.builtin.systemd:
        name: KEKS_TODO.service
        state: restarted
        daemon_reload: yes
